title: Xavier Mu&ntilde;iz&rsquo;s resume
footnote: © 2023 Xavier Muñiz
#footnote: "&#169; 2023 Xavier Mu&ntilde;iz"
  
baseurl: 
url: ""

contact_methods:
  - { symbol_name: email,  url: "&#109;ailto&#58;&#120;avier&#64;&#120;mz&#46;io", title: "&#120;avier&#64;&#120;mz&#46;io", hint: "Send an email" }
  - { symbol_name: linkedin, url: "https://www.linkedin.com/in/xaviermuniz/", title: "linkedin.com/in/xaviermuniz", hint: "Visit LinkedIn profile" }
  - { symbol_name: telephone,  url: "tel:+1-214-364-4838", title: "+1 214-364-4838", hint: "Call 214-364-4838" }
  #  - { symbol_name: voicemail,  url: "tel:+1-123-456-7890", title: "+1 123-456-7890", caption: "Please leave a message, I'll respond within the next business day" }
  - { symbol_name: home, url: "https://maps.apple.com/?address=Seattle,%20WA,%20United%20States", title: "Seattle, WA", hint: "View Seattle on the map" }

github_repository:
  title: github.com/xmzio/resume
  url: https://github.com/xmzio/resume

google_analytics: G-C7JJW8DSQL

collections_dir: content
collections:
  skillsSoft:
    output: false
  skillsTechnical:
    output: false
  experience:
    output: false
  experiencePrevious:
    output: false
  education:
    output: false
